package com.bjjy.buildtalk.core.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bjjy.buildtalk.core.greendao.HistoryData;
import com.bjjy.buildtalk.app.User;

import com.bjjy.buildtalk.core.greendao.HistoryDataDao;
import com.bjjy.buildtalk.core.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyDataDaoConfig;
    private final DaoConfig userDaoConfig;

    private final HistoryDataDao historyDataDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyDataDaoConfig = daoConfigMap.get(HistoryDataDao.class).clone();
        historyDataDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        historyDataDao = new HistoryDataDao(historyDataDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(HistoryData.class, historyDataDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        historyDataDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public HistoryDataDao getHistoryDataDao() {
        return historyDataDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
