package com.bjjy.buildtalk.core.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bjjy.buildtalk.app.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, String.class, "user_id", false, "USER_ID");
        public final static Property HeadImage = new Property(2, String.class, "headImage", false, "HEAD_IMAGE");
        public final static Property NickName = new Property(3, String.class, "nickName", false, "NICK_NAME");
        public final static Property Mobile = new Property(4, String.class, "mobile", false, "MOBILE");
        public final static Property User_type = new Property(5, String.class, "user_type", false, "USER_TYPE");
        public final static Property UpdateStatus = new Property(6, String.class, "updateStatus", false, "UPDATE_STATUS");
        public final static Property BindStatus = new Property(7, String.class, "bindStatus", false, "BIND_STATUS");
        public final static Property Bg_pic = new Property(8, String.class, "bg_pic", false, "BG_PIC");
        public final static Property LoginStatus = new Property(9, boolean.class, "loginStatus", false, "LOGIN_STATUS");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" TEXT UNIQUE ," + // 1: user_id
                "\"HEAD_IMAGE\" TEXT," + // 2: headImage
                "\"NICK_NAME\" TEXT," + // 3: nickName
                "\"MOBILE\" TEXT," + // 4: mobile
                "\"USER_TYPE\" TEXT," + // 5: user_type
                "\"UPDATE_STATUS\" TEXT," + // 6: updateStatus
                "\"BIND_STATUS\" TEXT," + // 7: bindStatus
                "\"BG_PIC\" TEXT," + // 8: bg_pic
                "\"LOGIN_STATUS\" INTEGER NOT NULL );"); // 9: loginStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(2, user_id);
        }
 
        String headImage = entity.getHeadImage();
        if (headImage != null) {
            stmt.bindString(3, headImage);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(4, nickName);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(5, mobile);
        }
 
        String user_type = entity.getUser_type();
        if (user_type != null) {
            stmt.bindString(6, user_type);
        }
 
        String updateStatus = entity.getUpdateStatus();
        if (updateStatus != null) {
            stmt.bindString(7, updateStatus);
        }
 
        String bindStatus = entity.getBindStatus();
        if (bindStatus != null) {
            stmt.bindString(8, bindStatus);
        }
 
        String bg_pic = entity.getBg_pic();
        if (bg_pic != null) {
            stmt.bindString(9, bg_pic);
        }
        stmt.bindLong(10, entity.getLoginStatus() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(2, user_id);
        }
 
        String headImage = entity.getHeadImage();
        if (headImage != null) {
            stmt.bindString(3, headImage);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(4, nickName);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(5, mobile);
        }
 
        String user_type = entity.getUser_type();
        if (user_type != null) {
            stmt.bindString(6, user_type);
        }
 
        String updateStatus = entity.getUpdateStatus();
        if (updateStatus != null) {
            stmt.bindString(7, updateStatus);
        }
 
        String bindStatus = entity.getBindStatus();
        if (bindStatus != null) {
            stmt.bindString(8, bindStatus);
        }
 
        String bg_pic = entity.getBg_pic();
        if (bg_pic != null) {
            stmt.bindString(9, bg_pic);
        }
        stmt.bindLong(10, entity.getLoginStatus() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // headImage
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // nickName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mobile
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // user_type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // updateStatus
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // bindStatus
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // bg_pic
            cursor.getShort(offset + 9) != 0 // loginStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHeadImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNickName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMobile(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUser_type(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUpdateStatus(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBindStatus(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBg_pic(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLoginStatus(cursor.getShort(offset + 9) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
